
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 30 } %>


development:
  <<: *default
  database: style_myle_version
  username: rubyuser
  password: postgres
  host: localhost
  port: 25432

test:
  <<: *default
  database: style_myle_version
  username: postgres
  password: etika@stylemyle
  host: localhost
  port: 25432

staging:
  <<: *default
  database: style_myle_version
  username: postgres
  password: etika@stylemyle

production:
  <<: *default
  host: localhost
  database: style_myle_version
  username: postgres
  password: etika@stylemyle

